version: 2.1

executors:
  default-executor:
    machine: true
    resource_class: ternandsparrow/fatty-webpack

jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-deps-{{ checksum "yarn.lock" }}
            - v3-deps

      - run:
          name: 'Install dependencies'
          command: |
            yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v3-deps-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths: .

  check-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run lint check'
          command: yarn lint:check

  run-unit-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run unit tests'
          # FIXME short-term grace period to allow us to build with failing tests
          command: yarn test:unit || [ $(date +%s) -lt $(date -d 2022-07-07 +%s) ]

  build-prod:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Write env var overrides'
          # we need to escape (\) the << otherwise CircleCI complains
          command: |
            theFile=.env.local
            cat \<<EOF > $theFile
            VUE_APP_INAT_BASE_URL=${PROD_INAT_BASE_URL:?}
            VUE_APP_INAT_STATIC_BASE_URL=${PROD_INAT_STATIC_BASE_URL:?}
            VUE_APP_API_BASE_URL=${PROD_API_BASE_URL:?}
            VUE_APP_FACADE_BASE_URL=${PROD_FACADE_BASE_URL:?}
            VUE_APP_OAUTH_APP_ID=${PROD_OAUTH_APP_ID:?}
            VUE_APP_OAUTH_REDIRECT_URI=${PROD_OAUTH_REDIRECT_URI:?}
            VUE_APP_INAT_PROJECT_SLUG=${PROD_INAT_PROJECT_SLUG:?}
            VUE_APP_OBS_FIELD_IDS_COARSE_FRAGMENTS=${PROD_OBS_FIELD_IDS_COARSE_FRAGMENTS:?}
            VUE_APP_OBS_FIELD_IDS_EVIDENCE_THREATS=${PROD_OBS_FIELD_IDS_EVIDENCE_THREATS:?}
            VUE_APP_OBS_FIELD_IDS_FLORAL_VISITORS=${PROD_OBS_FIELD_IDS_FLORAL_VISITORS:?}
            VUE_APP_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT=${PROD_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT:?}
            VUE_APP_OBS_FIELD_IDS_PHENOLOGY=${PROD_OBS_FIELD_IDS_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_IDS_WIDE_SELECTS=${PROD_OBS_FIELD_IDS_WIDE_SELECTS:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT=${PROD_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC=${PROD_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC:?}
            VUE_APP_OBS_FIELD_ID_AREA_OF_POPULATION=${PROD_OBS_FIELD_ID_AREA_OF_POPULATION:?}
            VUE_APP_OBS_FIELD_ID_AREA_SEARCHED=${PROD_OBS_FIELD_ID_AREA_SEARCHED:?}
            VUE_APP_OBS_FIELD_ID_COMMUNITY_NOTES=${PROD_OBS_FIELD_ID_COMMUNITY_NOTES:?}
            VUE_APP_OBS_FIELD_ID_COUNT=${PROD_OBS_FIELD_ID_COUNT:?}
            VUE_APP_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM=${PROD_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_PHENOLOGY=${PROD_OBS_FIELD_ID_DOMINANT_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_VEG=${PROD_OBS_FIELD_ID_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_EPIPHYTE_HEIGHT=${PROD_OBS_FIELD_ID_EPIPHYTE_HEIGHT:?}
            VUE_APP_OBS_FIELD_ID_FLORIVORY_DAMAGE=${PROD_OBS_FIELD_ID_FLORIVORY_DAMAGE:?}
            VUE_APP_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG=${PROD_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_HOST_TREE=${PROD_OBS_FIELD_ID_HOST_TREE:?}
            VUE_APP_OBS_FIELD_ID_IMMEDIATE_LANDUSE=${PROD_OBS_FIELD_ID_IMMEDIATE_LANDUSE:?}
            VUE_APP_OBS_FIELD_ID_LANDFORM_TYPE=${PROD_OBS_FIELD_ID_LANDFORM_TYPE:?}
            VUE_APP_OBS_FIELD_ID_LITTER=${PROD_OBS_FIELD_ID_LITTER:?}
            VUE_APP_OBS_FIELD_ID_ORCHID_TYPE=${PROD_OBS_FIELD_ID_ORCHID_TYPE:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH=${PROD_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH=${PROD_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_EFFORT=${PROD_OBS_FIELD_ID_SEARCH_EFFORT:?}
            VUE_APP_OBS_FIELD_ID_SOIL_STRUCTURE=${PROD_OBS_FIELD_ID_SOIL_STRUCTURE:?}
            VUE_APP_OBS_FIELD_ID_WIDER_LANDUSE=${PROD_OBS_FIELD_ID_WIDER_LANDUSE:?}
            VUE_APP_GA_CODE=${PROD_GA_CODE:?}
            VUE_APP_DEPLOYED_ENV_NAME=production
            VUE_APP_GMAPS_API_KEY=${PROD_GMAPS_API_KEY:?}
            VUE_APP_SENTRY_DSN=${SENTRY_DSN:?}
            # optional items
            VUE_APP_BBOX_LAT_MIN=$PROD_BBOX_LAT_MIN
            VUE_APP_BBOX_LAT_MAX=$PROD_BBOX_LAT_MAX
            VUE_APP_BBOX_LON_MIN=$PROD_BBOX_LON_MIN
            VUE_APP_BBOX_LON_MAX=$PROD_BBOX_LON_MAX
            VUE_APP_OBS_FIELD_DEFAULT_ACCURACY=$PROD_OBS_FIELD_DEFAULT_ACCURACY
            VUE_APP_OBS_FIELD_ORCHID_TYPE_EPIPHYTE=$PROD_OBS_FIELD_ORCHID_TYPE_EPIPHYTE
            VUE_APP_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL=$PROD_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL
            VUE_APP_OBS_FIELD_ACCURACY_PRECISE=$PROD_OBS_FIELD_ACCURACY_PRECISE
            VUE_APP_OBS_FIELD_ACCURACY_ESTIMATED=$PROD_OBS_FIELD_ACCURACY_ESTIMATED
            VUE_APP_NOT_COLLECTED=$PROD_NOT_COLLECTED
            VUE_APP_FEATURE_FLAG_MISSIONS=$PROD_FEATURE_FLAG_MISSIONS
            VUE_APP_FEATURE_FLAG_NEWS=$PROD_FEATURE_FLAG_NEWS
            VUE_APP_FEATURE_FLAG_DRAFT=$PROD_FEATURE_FLAG_DRAFT
            VUE_APP_FEATURE_FLAG_BUG_REPORT=$PROD_FEATURE_FLAG_BUG_REPORT
            VUE_APP_MAX_SW_REQ_FAIL_COUNT=$PROD_MAX_SW_REQ_FAIL_COUNT
            VUE_APP_FORCE_VUE_DEVTOOLS=$PROD_FORCE_VUE_DEVTOOLS
            VUE_APP_GCP_ERRORS_API_KEY=$PROD_GCP_ERRORS_API_KEY
            VUE_APP_SW_QUEUE_MAX_RETENTION=$PROD_SW_QUEUE_MAX_RETENTION
            VUE_APP_ENABLE_WORKBOX_LOGGING=${PROD_ENABLE_WORKBOX_LOGGING:-false}
            VUE_APP_PHOTO_COMP_JPEG_QUAL=${PROD_PHOTO_COMP_JPEG_QUAL}
            VUE_APP_PUBLIC_JWK=${PROD_PUBLIC_JWK}
            VUE_APP_STUCK_WITH_SW_MINUTES=${PROD_STUCK_WITH_SW_MINUTES}
            EOF
            echo "[INFO] contents of $theFile"
            cat $theFile
      - run:
          name: 'Build prod'
          command: |
            export VUE_APP_DEPLOYED_ENV_NAME=production
            ./scripts/build-and-sentry-release.sh
      - persist_to_workspace: # FIXME only need dist/ right?
          root: .
          paths: .

  build-beta:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Write env var overrides'
          # we need to escape (\) the << otherwise CircleCI complains
          command: |
            theFile=.env.local
            cat \<<EOF > $theFile
            VUE_APP_INAT_BASE_URL=${BETA_INAT_BASE_URL:?}
            VUE_APP_INAT_STATIC_BASE_URL=${BETA_INAT_STATIC_BASE_URL:?}
            VUE_APP_API_BASE_URL=${BETA_API_BASE_URL:?}
            VUE_APP_FACADE_BASE_URL=${BETA_FACADE_BASE_URL:?}
            VUE_APP_OAUTH_APP_ID=${BETA_OAUTH_APP_ID:?}
            VUE_APP_OAUTH_REDIRECT_URI=${BETA_OAUTH_REDIRECT_URI:?}
            VUE_APP_INAT_PROJECT_SLUG=${BETA_INAT_PROJECT_SLUG:?}
            VUE_APP_OBS_FIELD_IDS_COARSE_FRAGMENTS=${BETA_OBS_FIELD_IDS_COARSE_FRAGMENTS:?}
            VUE_APP_OBS_FIELD_IDS_EVIDENCE_THREATS=${BETA_OBS_FIELD_IDS_EVIDENCE_THREATS:?}
            VUE_APP_OBS_FIELD_IDS_FLORAL_VISITORS=${BETA_OBS_FIELD_IDS_FLORAL_VISITORS:?}
            VUE_APP_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT=${BETA_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT:?}
            VUE_APP_OBS_FIELD_IDS_PHENOLOGY=${BETA_OBS_FIELD_IDS_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_IDS_WIDE_SELECTS=${BETA_OBS_FIELD_IDS_WIDE_SELECTS:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT=${BETA_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC=${BETA_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC:?}
            VUE_APP_OBS_FIELD_ID_AREA_OF_POPULATION=${BETA_OBS_FIELD_ID_AREA_OF_POPULATION:?}
            VUE_APP_OBS_FIELD_ID_AREA_SEARCHED=${BETA_OBS_FIELD_ID_AREA_SEARCHED:?}
            VUE_APP_OBS_FIELD_ID_COMMUNITY_NOTES=${BETA_OBS_FIELD_ID_COMMUNITY_NOTES:?}
            VUE_APP_OBS_FIELD_ID_COUNT=${BETA_OBS_FIELD_ID_COUNT:?}
            VUE_APP_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM=${BETA_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_PHENOLOGY=${BETA_OBS_FIELD_ID_DOMINANT_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_VEG=${BETA_OBS_FIELD_ID_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_EPIPHYTE_HEIGHT=${BETA_OBS_FIELD_ID_EPIPHYTE_HEIGHT:?}
            VUE_APP_OBS_FIELD_ID_FLORIVORY_DAMAGE=${BETA_OBS_FIELD_ID_FLORIVORY_DAMAGE:?}
            VUE_APP_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG=${BETA_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_HOST_TREE=${BETA_OBS_FIELD_ID_HOST_TREE:?}
            VUE_APP_OBS_FIELD_ID_IMMEDIATE_LANDUSE=${BETA_OBS_FIELD_ID_IMMEDIATE_LANDUSE:?}
            VUE_APP_OBS_FIELD_ID_LANDFORM_TYPE=${BETA_OBS_FIELD_ID_LANDFORM_TYPE:?}
            VUE_APP_OBS_FIELD_ID_LITTER=${BETA_OBS_FIELD_ID_LITTER:?}
            VUE_APP_OBS_FIELD_ID_ORCHID_TYPE=${BETA_OBS_FIELD_ID_ORCHID_TYPE:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH=${BETA_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH=${BETA_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_EFFORT=${BETA_OBS_FIELD_ID_SEARCH_EFFORT:?}
            VUE_APP_OBS_FIELD_ID_SOIL_STRUCTURE=${BETA_OBS_FIELD_ID_SOIL_STRUCTURE:?}
            VUE_APP_OBS_FIELD_ID_WIDER_LANDUSE=${BETA_OBS_FIELD_ID_WIDER_LANDUSE:?}
            VUE_APP_GA_CODE=${BETA_GA_CODE:?}
            VUE_APP_DEPLOYED_ENV_NAME=beta
            VUE_APP_GMAPS_API_KEY=${BETA_GMAPS_API_KEY:?}
            VUE_APP_SENTRY_DSN=${SENTRY_DSN:?}
            # optional items
            VUE_APP_BBOX_LAT_MIN=$BETA_BBOX_LAT_MIN
            VUE_APP_BBOX_LAT_MAX=$BETA_BBOX_LAT_MAX
            VUE_APP_BBOX_LON_MIN=$BETA_BBOX_LON_MIN
            VUE_APP_BBOX_LON_MAX=$BETA_BBOX_LON_MAX
            VUE_APP_OBS_FIELD_DEFAULT_ACCURACY=$BETA_OBS_FIELD_DEFAULT_ACCURACY
            VUE_APP_OBS_FIELD_ORCHID_TYPE_EPIPHYTE=$BETA_OBS_FIELD_ORCHID_TYPE_EPIPHYTE
            VUE_APP_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL=$BETA_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL
            VUE_APP_OBS_FIELD_ACCURACY_PRECISE=$BETA_OBS_FIELD_ACCURACY_PRECISE
            VUE_APP_OBS_FIELD_ACCURACY_ESTIMATED=$BETA_OBS_FIELD_ACCURACY_ESTIMATED
            VUE_APP_NOT_COLLECTED=$BETA_NOT_COLLECTED
            VUE_APP_FEATURE_FLAG_MISSIONS=$BETA_FEATURE_FLAG_MISSIONS
            VUE_APP_FEATURE_FLAG_NEWS=$BETA_FEATURE_FLAG_NEWS
            VUE_APP_FEATURE_FLAG_DRAFT=$BETA_FEATURE_FLAG_DRAFT
            VUE_APP_FEATURE_FLAG_BUG_REPORT=$BETA_FEATURE_FLAG_BUG_REPORT
            VUE_APP_MAX_SW_REQ_FAIL_COUNT=$BETA_MAX_SW_REQ_FAIL_COUNT
            VUE_APP_FORCE_VUE_DEVTOOLS=$BETA_FORCE_VUE_DEVTOOLS
            VUE_APP_GCP_ERRORS_API_KEY=$BETA_GCP_ERRORS_API_KEY
            VUE_APP_SW_QUEUE_MAX_RETENTION=$BETA_SW_QUEUE_MAX_RETENTION
            VUE_APP_ENABLE_WORKBOX_LOGGING=${BETA_ENABLE_WORKBOX_LOGGING:-true}
            VUE_APP_PHOTO_COMP_JPEG_QUAL=${BETA_PHOTO_COMP_JPEG_QUAL}
            VUE_APP_PUBLIC_JWK=${BETA_PUBLIC_JWK}
            VUE_APP_STUCK_WITH_SW_MINUTES=${BETA_STUCK_WITH_SW_MINUTES}
            EOF
            echo "[INFO] contents of $theFile"
            cat $theFile
      - run:
          name: 'Build beta'
          command: |
            export VUE_APP_DEPLOYED_ENV_NAME=beta
            ./scripts/build-and-sentry-release.sh
      - persist_to_workspace: # FIXME only need dist/ right?
          root: .
          paths: .

  build-dev:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Write env var overrides'
          # we need to escape (\) the << otherwise CircleCI complains
          command: |
            theFile=.env.local
            cat \<<EOF > $theFile
            VUE_APP_INAT_BASE_URL=${DEV_INAT_BASE_URL:?}
            VUE_APP_INAT_STATIC_BASE_URL=${DEV_INAT_STATIC_BASE_URL:?}
            VUE_APP_API_BASE_URL=${DEV_API_BASE_URL:?}
            VUE_APP_FACADE_BASE_URL=${DEV_FACADE_BASE_URL:?}
            VUE_APP_OAUTH_APP_ID=${DEV_OAUTH_APP_ID:?}
            VUE_APP_OAUTH_REDIRECT_URI=${DEV_OAUTH_REDIRECT_URI:?}
            VUE_APP_INAT_PROJECT_SLUG=${DEV_INAT_PROJECT_SLUG:?}
            VUE_APP_OBS_FIELD_IDS_COARSE_FRAGMENTS=${DEV_OBS_FIELD_IDS_COARSE_FRAGMENTS:?}
            VUE_APP_OBS_FIELD_IDS_EVIDENCE_THREATS=${DEV_OBS_FIELD_IDS_EVIDENCE_THREATS:?}
            VUE_APP_OBS_FIELD_IDS_FLORAL_VISITORS=${DEV_OBS_FIELD_IDS_FLORAL_VISITORS:?}
            VUE_APP_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT=${DEV_OBS_FIELD_IDS_MUTUALLY_EXCLUSIVE_MULTISELECT:?}
            VUE_APP_OBS_FIELD_IDS_PHENOLOGY=${DEV_OBS_FIELD_IDS_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_IDS_WIDE_SELECTS=${DEV_OBS_FIELD_IDS_WIDE_SELECTS:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT=${DEV_OBS_FIELD_ID_ACCURACY_OF_POPULATION_COUNT:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC=${DEV_OBS_FIELD_ID_ACCURACY_OF_SEARCH_AREA_CALC:?}
            VUE_APP_OBS_FIELD_ID_AREA_OF_POPULATION=${DEV_OBS_FIELD_ID_AREA_OF_POPULATION:?}
            VUE_APP_OBS_FIELD_ID_AREA_SEARCHED=${DEV_OBS_FIELD_ID_AREA_SEARCHED:?}
            VUE_APP_OBS_FIELD_ID_COMMUNITY_NOTES=${DEV_OBS_FIELD_ID_COMMUNITY_NOTES:?}
            VUE_APP_OBS_FIELD_ID_COUNT=${DEV_OBS_FIELD_ID_COUNT:?}
            VUE_APP_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM=${DEV_OBS_FIELD_ID_COVER_OF_DOMINANT_STRATUM:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_PHENOLOGY=${DEV_OBS_FIELD_ID_DOMINANT_PHENOLOGY:?}
            VUE_APP_OBS_FIELD_ID_DOMINANT_VEG=${DEV_OBS_FIELD_ID_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_EPIPHYTE_HEIGHT=${DEV_OBS_FIELD_ID_EPIPHYTE_HEIGHT:?}
            VUE_APP_OBS_FIELD_ID_FLORIVORY_DAMAGE=${DEV_OBS_FIELD_ID_FLORIVORY_DAMAGE:?}
            VUE_APP_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG=${DEV_OBS_FIELD_ID_HEIGHT_OF_DOMINANT_VEG:?}
            VUE_APP_OBS_FIELD_ID_HOST_TREE=${DEV_OBS_FIELD_ID_HOST_TREE:?}
            VUE_APP_OBS_FIELD_ID_IMMEDIATE_LANDUSE=${DEV_OBS_FIELD_ID_IMMEDIATE_LANDUSE:?}
            VUE_APP_OBS_FIELD_ID_LANDFORM_TYPE=${DEV_OBS_FIELD_ID_LANDFORM_TYPE:?}
            VUE_APP_OBS_FIELD_ID_LITTER=${DEV_OBS_FIELD_ID_LITTER:?}
            VUE_APP_OBS_FIELD_ID_ORCHID_TYPE=${DEV_OBS_FIELD_ID_ORCHID_TYPE:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH=${DEV_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_LENGTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH=${DEV_OBS_FIELD_ID_SEARCH_AREA_CALC_PRECISE_WIDTH:?}
            VUE_APP_OBS_FIELD_ID_SEARCH_EFFORT=${DEV_OBS_FIELD_ID_SEARCH_EFFORT:?}
            VUE_APP_OBS_FIELD_ID_SOIL_STRUCTURE=${DEV_OBS_FIELD_ID_SOIL_STRUCTURE:?}
            VUE_APP_OBS_FIELD_ID_WIDER_LANDUSE=${DEV_OBS_FIELD_ID_WIDER_LANDUSE:?}
            VUE_APP_GA_CODE=${DEV_GA_CODE:?}
            VUE_APP_DEPLOYED_ENV_NAME=development
            VUE_APP_GMAPS_API_KEY=${DEV_GMAPS_API_KEY:?}
            VUE_APP_SENTRY_DSN=${SENTRY_DSN:?}
            # optional items
            VUE_APP_BBOX_LAT_MIN=$DEV_BBOX_LAT_MIN
            VUE_APP_BBOX_LAT_MAX=$DEV_BBOX_LAT_MAX
            VUE_APP_BBOX_LON_MIN=$DEV_BBOX_LON_MIN
            VUE_APP_BBOX_LON_MAX=$DEV_BBOX_LON_MAX
            VUE_APP_OBS_FIELD_DEFAULT_ACCURACY=$DEV_OBS_FIELD_DEFAULT_ACCURACY
            VUE_APP_OBS_FIELD_ORCHID_TYPE_EPIPHYTE=$DEV_OBS_FIELD_ORCHID_TYPE_EPIPHYTE
            VUE_APP_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL=$DEV_OBS_FIELD_ORCHID_TYPE_TERRESTRIAL
            VUE_APP_OBS_FIELD_ACCURACY_PRECISE=$DEV_OBS_FIELD_ACCURACY_PRECISE
            VUE_APP_OBS_FIELD_ACCURACY_ESTIMATED=$DEV_OBS_FIELD_ACCURACY_ESTIMATED
            VUE_APP_NOT_COLLECTED=$DEV_NOT_COLLECTED
            VUE_APP_FEATURE_FLAG_MISSIONS=$DEV_FEATURE_FLAG_MISSIONS
            VUE_APP_FEATURE_FLAG_NEWS=$DEV_FEATURE_FLAG_NEWS
            VUE_APP_FEATURE_FLAG_DRAFT=$DEV_FEATURE_FLAG_DRAFT
            VUE_APP_FEATURE_FLAG_BUG_REPORT=$DEV_FEATURE_FLAG_BUG_REPORT
            VUE_APP_MAX_SW_REQ_FAIL_COUNT=$DEV_MAX_SW_REQ_FAIL_COUNT
            VUE_APP_FORCE_VUE_DEVTOOLS=$DEV_FORCE_VUE_DEVTOOLS
            VUE_APP_GCP_ERRORS_API_KEY=$DEV_GCP_ERRORS_API_KEY
            VUE_APP_SW_QUEUE_MAX_RETENTION=$DEV_SW_QUEUE_MAX_RETENTION
            VUE_APP_ENABLE_WORKBOX_LOGGING=${DEV_ENABLE_WORKBOX_LOGGING:-true}
            VUE_APP_PHOTO_COMP_JPEG_QUAL=${DEV_PHOTO_COMP_JPEG_QUAL}
            VUE_APP_PUBLIC_JWK=${DEV_PUBLIC_JWK}
            VUE_APP_STUCK_WITH_SW_MINUTES=${DEV_STUCK_WITH_SW_MINUTES}
            EOF
            echo "[INFO] contents of $theFile"
            cat $theFile
      - run:
          name: 'Build dev'
          command: |
            export VUE_APP_DEPLOYED_ENV_NAME=development
            ./scripts/build-and-sentry-release.sh
      - persist_to_workspace: # FIXME only need dist/ right?
          root: .
          paths: .

  deploy-prod:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy prod'
          command: |
            : ${FIREBASE_TOKEN:?}
            yarn firebase:deploy:ci prod

  deploy-beta:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy beta'
          command: |
            : ${FIREBASE_TOKEN:?}
            yarn firebase:deploy:ci beta

  deploy-dev:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy dev'
          command: |
            : ${FIREBASE_TOKEN:?}
            yarn firebase:deploy:ci dev

workflows:
  version: 2
  build-and-deploy-prod:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: master # dependent jobs are controlled by this
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - build-prod:
          requires:
            - check-linter
            - run-unit-tests
      - deploy-prod:
          requires:
            - build-prod

  build-and-deploy-beta:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: beta # dependent jobs are controlled by this
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - build-beta:
          requires:
            - check-linter
            - run-unit-tests
      - deploy-beta:
          requires:
            - build-beta

  build-everything-and-deploy-dev:
    jobs:
      - install-dependencies:
          filters:
            branches:
              ignore: # dependent jobs are controlled by this
                - beta
                - master
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - build-dev:
          requires:
            - check-linter
            - run-unit-tests
          filters:
            branches:
              only: develop # only build and deploy this branch
      - deploy-dev:
          requires:
            - build-dev
